version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sender-database
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sender
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sender-api
    networks:
      - internal

  redis:
    image: bitnami/redis:latest
    container_name: sender-redis
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      - internal

networks:
  internal:
    driver: bridge
